# Generated by Django 3.1.2 on 2020-10-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='pdf_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
