# Generated by Django 3.1.2 on 2020-10-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_text_pdf_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'get_latest_by': 'publication_date'},
        ),
        migrations.AddField(
            model_name='text',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
