# Generated by Django 3.1.2 on 2020-10-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201025_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='slug',
            field=models.SlugField(default='slug1'),
            preserve_default=False,
        ),
    ]
