# Generated by Django 3.1.2 on 2020-10-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_text_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('active', models.BooleanField()),
                ('staff_only', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='label',
            field=models.ManyToManyField(to='main.Label'),
        ),
    ]
