# Generated by Django 3.1.2 on 2020-11-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201030_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='public'),
        ),
        migrations.AlterField(
            model_name='text',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, to='main.Label'),
        ),
        migrations.AlterField(
            model_name='text',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='protected'),
        ),
    ]
